# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1090, 700)
        font = QtGui.QFont()
        font.setPointSize(10)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 30, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 170, 111, 20))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(380, 350, 371, 20))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 230, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 450, 711, 20))
        self.label_9.setObjectName("label_9")
        self.marital_status = QtWidgets.QLineEdit(self.centralwidget)
        self.marital_status.setGeometry(QtCore.QRect(330, 170, 113, 22))
        self.marital_status.setObjectName("marital_status")
        self.default_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.default_2.setGeometry(QtCore.QRect(330, 230, 113, 22))
        self.default_2.setObjectName("default_2")
        self.previous = QtWidgets.QLineEdit(self.centralwidget)
        self.previous.setGeometry(QtCore.QRect(780, 500, 113, 22))
        self.previous.setObjectName("previous")
        self.loan = QtWidgets.QLineEdit(self.centralwidget)
        self.loan.setGeometry(QtCore.QRect(780, 110, 113, 22))
        self.loan.setObjectName("loan")
        self.age = QtWidgets.QLineEdit(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(330, 110, 113, 22))
        self.age.setObjectName("age")
        self.balance = QtWidgets.QLineEdit(self.centralwidget)
        self.balance.setGeometry(QtCore.QRect(780, 170, 113, 22))
        self.balance.setObjectName("balance")
        self.pdays = QtWidgets.QLineEdit(self.centralwidget)
        self.pdays.setGeometry(QtCore.QRect(780, 450, 113, 22))
        self.pdays.setObjectName("pdays")
        self.day = QtWidgets.QLineEdit(self.centralwidget)
        self.day.setGeometry(QtCore.QRect(780, 350, 113, 22))
        self.day.setObjectName("day")
        self.housing = QtWidgets.QLineEdit(self.centralwidget)
        self.housing.setGeometry(QtCore.QRect(780, 230, 113, 22))
        self.housing.setObjectName("housing")
        self.campaign = QtWidgets.QLineEdit(self.centralwidget)
        self.campaign.setGeometry(QtCore.QRect(780, 400, 113, 22))
        self.campaign.setObjectName("campaign")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(690, 170, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(690, 230, 61, 21))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 110, 101, 21))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 500, 361, 20))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 570, 341, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(170, 400, 581, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(370, 300, 381, 21))
        self.label_11.setObjectName("label_11")
        self.education = QtWidgets.QLineEdit(self.centralwidget)
        self.education.setGeometry(QtCore.QRect(780, 300, 113, 22))
        self.education.setObjectName("education")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 29))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "Welcome to the system. Please follow the procedures"))
        self.label_2.setText(_translate("mainWindow", "Marital Status"))
        self.label_7.setText(_translate("mainWindow", "The day when you have last contacted with client"))
        self.label_3.setText(_translate("mainWindow", "Any Default Credit"))
        self.label_9.setText(_translate("mainWindow", "How many days passed since your last contact with client after last campaign? If none, enter -1"))
        self.label_5.setText(_translate("mainWindow", "Balance"))
        self.label_6.setText(_translate("mainWindow", "Housing"))
        self.label_4.setText(_translate("mainWindow", "Previous Loan"))
        self.label_8.setText(_translate("mainWindow", "Total number of contacts before this campaign?"))
        self.label_12.setText(_translate("mainWindow", "Age"))
        self.pushButton.setText(_translate("mainWindow", "Request For Loan"))
        self.label_10.setText(_translate("mainWindow", "How many times the client have been contacted during the current campaign?"))
        self.label_11.setText(_translate("mainWindow", "Education status? Primary or Secondary or Tertiary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

